/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Admin
 */
public class facturados extends javax.swing.JFrame {

    conexion cn = new conexion();
    Connection cnn = cn.conectar();
    DefaultTableModel pedido;

    /**
     * Creates new form facturados
     */
    public facturados() {
        initComponents();
        this.setExtendedState(facturados.MAXIMIZED_BOTH);
        this.pedido = (DefaultTableModel) pedido_tbl.getModel();
        mostrar_datos();
        totalf();
        cantf();
    }

    //OBTENER TOTAL DE DINERO DE LAS FACTURAS
    public void totalf() {

        Double total;
        String consulta = "SELECT SUM(total) FROM facturados;";
        try {
            PreparedStatement prst = cnn.prepareStatement(consulta);
            ResultSet res = prst.executeQuery(consulta);

            if (res.next()) {
                total = res.getDouble(1);

                dinero_fact_txt.setText(Double.toString(total));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "error" + ex);
        }
    }

    //CANTIDAD DE PEDIDOS FACTURADOS
    public void cantf() {

        int cant;
        String consulta = "SELECT COUNT(*) FROM facturados;";
        try {
            PreparedStatement prst = cnn.prepareStatement(consulta);
            ResultSet res = prst.executeQuery(consulta);

            if (res.next()) {
                cant = res.getInt(1);

                ped_fac_txt.setText(Integer.toString(cant));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "error" + ex);
        }
    }

    //REFRESCAR LA TABLA
    public void refrescar() {
        try {
            pedido.setColumnCount(0);
            pedido.setRowCount(0);
            pedido_tbl.revalidate();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex);
        }
    }

//MOSTRAR DATOS DE LA TABLA
    public void mostrar_datos() {

        refrescar();

        pedido.addColumn("Factura");
        pedido.addColumn("Pedido");
        pedido.addColumn("Producto");
        pedido.addColumn("RNC cliente");
        pedido.addColumn("Cliente");
        pedido.addColumn("Total");

        this.pedido_tbl.setModel(pedido);
        String consul;
        consul = "SELECT * FROM facturados ORDER BY nf ASC";

        String[] datos = new String[6];
        try {
            Statement st = cnn.createStatement();
            ResultSet rs = st.executeQuery(consul);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);

                pedido.addRow(datos);

            }

            pedido_tbl.setModel(pedido);
        } catch (SQLException ex) {
            Logger.getLogger(log_form.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error " + ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        azul_pnl = new javax.swing.JPanel();
        blanco_pnl = new javax.swing.JPanel();
        grupo_m_lbl = new javax.swing.JLabel();
        titulo_lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pedido_tbl = new javax.swing.JTable();
        pedidos_lbl = new javax.swing.JLabel();
        ped_fac_lbl = new javax.swing.JLabel();
        ped_fac_txt = new javax.swing.JTextField();
        atras_lbl = new javax.swing.JLabel();
        tot_dinero_lbl = new javax.swing.JLabel();
        dinero_fact_txt = new javax.swing.JTextField();
        no_f_lbl = new javax.swing.JLabel();
        cod_fact_txt = new javax.swing.JTextField();
        imp_btn = new javax.swing.JButton();
        reporte_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        azul_pnl.setBackground(new java.awt.Color(8, 41, 138));

        blanco_pnl.setBackground(new java.awt.Color(255, 255, 255));

        grupo_m_lbl.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        grupo_m_lbl.setForeground(new java.awt.Color(0, 0, 102));
        grupo_m_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo - 24x24.png"))); // NOI18N
        grupo_m_lbl.setText("Grupo M");

        titulo_lbl.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        titulo_lbl.setForeground(new java.awt.Color(0, 0, 102));
        titulo_lbl.setText("Consultar Pedidos");

        pedido_tbl.setBackground(new java.awt.Color(255, 255, 255));
        pedido_tbl.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        pedido_tbl.setForeground(new java.awt.Color(0, 0, 0));
        pedido_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        pedido_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pedido_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pedido_tbl);

        pedidos_lbl.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        pedidos_lbl.setForeground(new java.awt.Color(0, 0, 102));
        pedidos_lbl.setText("Pedidos facturados");

        ped_fac_lbl.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        ped_fac_lbl.setForeground(new java.awt.Color(0, 0, 102));
        ped_fac_lbl.setText("Total de pedidos facturados");

        ped_fac_txt.setBackground(new java.awt.Color(255, 255, 255));
        ped_fac_txt.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        ped_fac_txt.setForeground(new java.awt.Color(0, 0, 0));
        ped_fac_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        ped_fac_txt.setEnabled(false);

        atras_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_undo_24px.png"))); // NOI18N
        atras_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atras_lblMouseClicked(evt);
            }
        });

        tot_dinero_lbl.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        tot_dinero_lbl.setForeground(new java.awt.Color(0, 0, 102));
        tot_dinero_lbl.setText("Total de dinero");

        dinero_fact_txt.setBackground(new java.awt.Color(255, 255, 255));
        dinero_fact_txt.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        dinero_fact_txt.setForeground(new java.awt.Color(0, 0, 0));
        dinero_fact_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        dinero_fact_txt.setEnabled(false);

        no_f_lbl.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        no_f_lbl.setForeground(new java.awt.Color(0, 0, 102));
        no_f_lbl.setText("Número de factura");

        cod_fact_txt.setBackground(new java.awt.Color(255, 255, 255));
        cod_fact_txt.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        cod_fact_txt.setForeground(new java.awt.Color(0, 0, 0));
        cod_fact_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        cod_fact_txt.setEnabled(false);

        imp_btn.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        imp_btn.setForeground(new java.awt.Color(0, 0, 102));
        imp_btn.setText("IMPRIMIR FACTURA");
        imp_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imp_btn.setContentAreaFilled(false);
        imp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imp_btnActionPerformed(evt);
            }
        });

        reporte_btn.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        reporte_btn.setForeground(new java.awt.Color(0, 0, 102));
        reporte_btn.setText("REPORTE");
        reporte_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reporte_btn.setContentAreaFilled(false);
        reporte_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporte_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout blanco_pnlLayout = new javax.swing.GroupLayout(blanco_pnl);
        blanco_pnl.setLayout(blanco_pnlLayout);
        blanco_pnlLayout.setHorizontalGroup(
            blanco_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blanco_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(blanco_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(blanco_pnlLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(blanco_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(blanco_pnlLayout.createSequentialGroup()
                                .addComponent(ped_fac_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(dinero_fact_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(cod_fact_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addGroup(blanco_pnlLayout.createSequentialGroup()
                                .addGroup(blanco_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ped_fac_lbl)
                                    .addComponent(tot_dinero_lbl)
                                    .addComponent(no_f_lbl))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(imp_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reporte_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(blanco_pnlLayout.createSequentialGroup()
                        .addComponent(grupo_m_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(titulo_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atras_lbl))
                    .addGroup(blanco_pnlLayout.createSequentialGroup()
                        .addComponent(pedidos_lbl)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        blanco_pnlLayout.setVerticalGroup(
            blanco_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blanco_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(blanco_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(atras_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grupo_m_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pedidos_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blanco_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addGroup(blanco_pnlLayout.createSequentialGroup()
                        .addComponent(ped_fac_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ped_fac_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tot_dinero_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dinero_fact_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(no_f_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cod_fact_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imp_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reporte_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout azul_pnlLayout = new javax.swing.GroupLayout(azul_pnl);
        azul_pnl.setLayout(azul_pnlLayout);
        azul_pnlLayout.setHorizontalGroup(
            azul_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(azul_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blanco_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        azul_pnlLayout.setVerticalGroup(
            azul_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(azul_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blanco_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(azul_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(azul_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atras_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atras_lblMouseClicked
        //PANTALLA DE VENTAS
        ventas frame = new ventas();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_atras_lblMouseClicked

    private void pedido_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedido_tblMouseClicked
        //RELLENAR LOS TEXTFIELDS

        try {

            String cod = (String) pedido.getValueAt(pedido_tbl.getSelectedRow(), 0);

            cod_fact_txt.setText(cod);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "error " + ex);
        }
    }//GEN-LAST:event_pedido_tblMouseClicked

    private void imp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imp_btnActionPerformed
        //MOSTRAR FACTURAS
        Connection cn = conexion.conectar();

        try {
            String factura = cod_fact_txt.getText();
            JasperReport jr = (JasperReport) JRLoader.loadObject(facturar.class.getResource("/reportes/factura.jasper"));
            Map parametro = new HashMap<>();
            parametro.put("factura", factura);
            JasperPrint jp = JasperFillManager.fillReport(jr, parametro, cnn);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }//GEN-LAST:event_imp_btnActionPerformed

    private void reporte_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporte_btnActionPerformed
        //REPORTE DE PEDIDOS FACTURADOS
        Connection cn = conexion.conectar();

        try {
            JasperReport jr = (JasperReport) JRLoader.loadObject(recursos_humanos.class.getResource("/reportes/facturados.jasper"));
            Map parametros = new HashMap<>();
            parametros.put("Titulo", "Cliente");

            JasperPrint jp = JasperFillManager.fillReport(jr, parametros, cn);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_reporte_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facturados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facturados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facturados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facturados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new facturados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atras_lbl;
    private javax.swing.JPanel azul_pnl;
    private javax.swing.JPanel blanco_pnl;
    private javax.swing.JTextField cod_fact_txt;
    private javax.swing.JTextField dinero_fact_txt;
    private javax.swing.JLabel grupo_m_lbl;
    private javax.swing.JButton imp_btn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel no_f_lbl;
    private javax.swing.JLabel ped_fac_lbl;
    private javax.swing.JTextField ped_fac_txt;
    private javax.swing.JTable pedido_tbl;
    private javax.swing.JLabel pedidos_lbl;
    private javax.swing.JButton reporte_btn;
    private javax.swing.JLabel titulo_lbl;
    private javax.swing.JLabel tot_dinero_lbl;
    // End of variables declaration//GEN-END:variables
}
